name: CyberPolice

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: "YouTube URL"
        required: true

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run AI detection
        run: python youtube_monitor.py
        env:
          VIDEO_URL: ${{ github.event.inputs.video_url }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: cyberpolice-report
          path: report.json
         
